### PR TITLE
fixes #124 honor quarkus.scheduler.enabled property

### LINKED ISSUE #124: Quarkus scheduler does not honor scheduler.enabled property
**Describe the bug**
Quarkus has a `quarkus.scheduler.enabled` property that should enable/disable all scheduling jobs. The GreenScheduler does not honor that setting.

**Context**
In e.g. test runs, a predictable database and/or processlist is required. The greenscheduler should thus also be predictable and at least be disabled when testing.
This is often done by:
```
# disable jobs when testing, since they will add noise to the test results
%test.quarkus.scheduler.enabled=false
``` 
However, this does not work.

**Environment**
Any environment.

**Expected behavior**
If `quarkus.scheduler.enabled=false`, scheduled jobs including the green scheduler should not run.

**Actual behavior**
The jobs do run (if the tests are run at the greenest moment).

**Relevant Logs/Output**
n.a.

**To Reproduce**
1. Create a Quarkus Integration test that runs for a while
2. In that same application, have a green scheduled job with a 24h window (allow any time)
3. Set `%test.quarkus.scheduler.enabled=false` in `application.properties`
4. Run the test in a green window
5. Observe that the scheduled job runs

**Version**
```
        <dependency>
            <groupId>io.carbonintensity</groupId>
            <artifactId>quarkus-green-scheduler</artifactId>
            <version>0.8.2</version>
        </dependency>
```

**Possible Solution**
Honor the setting.

**Additional context**
In test settings, it might be useful to steer the 'greenest' window to something control by the test. For now, being able to disable the tests is already sufficient.

### PR DESCRIPTION
**Pull request by willlie1**
## Type of Change
Please delete options that are not relevant
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Related Issues
#124 

## Checklist
- [x] Formatted according to the  [CONTRIBUTING guidelines](https://github.com/carbonintensityio/scheduler/blob/main/CONTRIBUTING.md)
- [x] Follows the [coding guidelines](https://github.com/carbonintensityio/scheduler/blob/main/CONTRIBUTING.md#coding-guidelines)
- [x] Follows the [logging guidelines](https://github.com/carbonintensityio/scheduler/blob/main/CONTRIBUTING.md#logging-guidelines)
- [x] Tests are added
- [x] Build runs successfully

-------

### CODE REVIEW

File: extensions/quarkus/deployment/src/main/java/io/carbonintensity/scheduler/quarkus/deployment/SchedulerProcessor.java [hunk 1]
```diff
@@ -90,6 +92,17 @@ NativeImageResourceDirectoryBuildItem nativeImageResourceBuildItem() {
         return new NativeImageResourceDirectoryBuildItem("fallback");
     }
 
+    @BuildStep
+    void registerQuarkusSchedulerDisableProperty(BuildProducer<ConfigDescriptionBuildItem> configDescriptions) {
+        configDescriptions.produce(new ConfigDescriptionBuildItem(
+                "quarkus.scheduler.enabled",
+                "Enables the Quarkus scheduler component. When disabled, the Green Scheduler stays off as well.",
+                "true",
```
Comment (fnikscon) [inline extensions/quarkus/deployment/src/main/java/io/carbonintensity/scheduler/quarkus/deployment/SchedulerProcessor.java]: Shouldn't the values for the 2nd parameter (defaultValue) and 3rd parameter (docs) be the other way around?

Comment (willlie1) [reply extensions/quarkus/deployment/src/main/java/io/carbonintensity/scheduler/quarkus/deployment/SchedulerProcessor.java]: yup idd, good catch
